version: "3.9"

services:
  backend:
    build:
      context: ./wms-demo/backend
    volumes:
      - ./wms-demo/backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - server

  frontend:
    build:
      context: ./wms-demo/frontend/API-Demo
    ports:
      - "4173:4173"
    environment:
      - PUBLIC_API_BASE=/api
      - INTERNAL_API_BASE=http://backend:8000
    depends_on:
      - backend
    networks:
      - server

networks:
  server:
    external: true
